text: 开发环境
server:
  ip: localhost

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hamburgmall
    username: root
    password: root

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

  mail:
    host: smtp.qq.com
    port: 587
    username: 1244943676@qq.com
    password: ogurwryppcdmgcgh


files:
  uploads:
    path: E:\images\


