


server:
  port: 8282
spring:
  profiles:
    active: dev



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: com/ldw/mapper/xml/*.xml
  mvc:
    path match:
      matching-strategy: ant_path_matcher
